server.port=9191

# Route requests to services using Eureka names (lb://)
spring.cloud.gateway.routes[0].id=quiz-route
spring.cloud.gateway.routes[0].uri=lb://QUIZSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/quiz/**

spring.cloud.gateway.routes[1].id=question-route
spring.cloud.gateway.routes[1].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/questions/**
