server.port=9191

# Service Discovery (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Route for Service One
spring.cloud.gateway.routes[0].id=quiz-route
spring.cloud.gateway.routes[0].uri=lb://QUIZSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/quiz/**

# Route for Service Two
spring.cloud.gateway.routes[1].id=question-route
spring.cloud.gateway.routes[1].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/questions/**

# Route for Service Three
spring.cloud.gateway.routes[1].id=authservice-route
spring.cloud.gateway.routes[1].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**
